services:
  - type: web
    name: student-success-system
    env: static
    buildCommand: echo "No build needed"
    staticPublishPath: ./frontend
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
